- name: Launch backend container
  community.docker.docker_container:
    name: backend
    image: kintz53/tp-devops-simple-api:latest
    state: started
    restart_policy: always
    pull: true
    docker_host: unix:///var/run/docker.sock
    networks:
      - name: app-network
    env:
      DB_HOST: database
      DB_NAME: "{{ db_name }}"
      DB_USER: "{{ db_user }}"
      DB_PASSWORD: "{{ db_password }}"
